#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 08, 2019 04:47:15 PM IST  platform: Windows NT

import sys
import subprocess
import os

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

from PIL import Image, ImageTk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import akhil_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel(root)
    akhil_support.init(root, top)
    root.mainloop()


w = None


def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = New_Toplevel(w)
    akhil_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#5b9ed8'  # Closest X11 color: 'SteelBlue3'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d8955b'  # Closest X11 color: 'LightSalmon3'
        _ana1color = '#5b5fd8'  # Closest X11 color: 'SlateBlue3'
        _ana2color = '#5bd8d4'  # Closest X11 color: '{medium turquoise}'
        font11 = "-family {Product Sans} -size 16 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font13 = "-family {Product Sans} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=[
                       ('selected', _compcolor), ('active', _ana2color)])

        top.geometry("1068x906+216+41")
        top.title("New Toplevel")
        top.configure(background="#ffffff")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.0, rely=-0.011, height=116, width=1072)
        self.Label1.configure(background="#E91E63")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Computer Networks Project''')
        self.Label1.configure(width=1072)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.0, rely=0.949, height=46, width=1072)
        self.Label2.configure(background="#757575")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font13)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''Akhil Surendran © 17BCE7087''')
        self.Label2.configure(width=1072)

        def FTP():
            root.destroy()
            os.system('start ; py -2 task4_server.py')
            subprocess.call('python ftp.py')

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.037, rely=0.342, height=320, width=310)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Tbutton''')
        self.TButton1.configure(width=310)
        self._img1 = ImageTk.PhotoImage(Image.open("ftp2.png"))
        self.TButton1.configure(image=self._img1)
        self.TButton1.configure(command=FTP)

        def email():
            # root.destroy()
            subprocess.call('python mail.py')

        self.TButton1_5 = ttk.Button(top)
        self.TButton1_5.place(relx=0.356, rely=0.342, height=320, width=310)
        self.TButton1_5.configure(takefocus="")
        self.TButton1_5.configure(text='''Tbutton''')
        self._img2 = ImageTk.PhotoImage(Image.open("email.png"))
        self.TButton1_5.configure(image=self._img2)
        self.TButton1_5.configure(command=email)

        def downloader():
            root.destroy()
            subprocess.call('python downloader.py')

        self.TButton1_6 = ttk.Button(top)
        self.TButton1_6.place(relx=0.684, rely=0.342, height=320, width=310)
        self.TButton1_6.configure(takefocus="")
        self.TButton1_6.configure(text='''Tbutton''')
        self._img3 = ImageTk.PhotoImage(Image.open("download.png"))
        self.TButton1_6.configure(image=self._img3)
        self.TButton1_6.configure(command=downloader)

        def about():
            root.destroy()
            subprocess.call('python about.py')
        self.TButton2 = ttk.Button(top)
        self.TButton2.place(relx=0.384, rely=0.872, height=60, width=258)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''About this Project''')
        self.TButton2.configure(width=258)
        self.TButton2.configure(command=about)


if __name__ == '__main__':
    vp_start_gui()
