#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 08, 2019 08:52:53 PM IST  platform: Windows NT

import sys
import subprocess
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ftp_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = FTP(root)
    ftp_support.init(root, top)
    root.mainloop()


w = None


def create_FTP(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = FTP(w)
    ftp_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_FTP():
    global w
    w.destroy()
    w = None


class FTP:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#5b9ed8'  # Closest X11 color: 'SteelBlue3'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d8955b'  # Closest X11 color: 'LightSalmon3'
        _ana1color = '#5b5fd8'  # Closest X11 color: 'SlateBlue3'
        _ana2color = '#5bd8d4'  # Closest X11 color: '{medium turquoise}'
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {Product Sans} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Product Sans} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("799x764+451+150")
        top.title("FTP")
        top.configure(background="#fef7ff")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.0, rely=0.0, height=76, width=802)
        self.Label1.configure(background="#CDDC39")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#f7f7f7")
        self.Label1.configure(text='''File Transfer Protocol''')
        self.Label1.configure(width=802)

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.238, rely=0.288, height=54, relwidth=0.518)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font10)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=414)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.025, rely=0.196, height=56, width=752)
        self.Label2.configure(background="#fef7ff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Enter the name of the file''')
        self.Label2.configure(width=752)

        def transfer():
            a = self.Entry1.get()
            subprocess.call(f"py -2 task4_client.py {a} ")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.438, rely=0.393, height=33, width=115)
        self.Button1.configure(activebackground="#5bd8d4")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#F0F4C3")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font12)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#5b9ed8")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Transfer''')
        self.Button1.configure(width=115)
        self.Button1.configure(command=transfer)

        def back():
            root.destroy()
            subprocess.call('python akhil.py')

        self.Button1_1 = Button(top)
        self.Button1_1.place(relx=0.613, rely=0.393, height=33, width=115)
        self.Button1_1.configure(activebackground="#5bd8d4")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#F0F4C3")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font12)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#5b9ed8")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Go Back''')
        self.Button1_1.configure(command=back)


if __name__ == '__main__':
    vp_start_gui()
